enum CONSTANTS {
  SET_DATA_LIST = 'SET_DATA_LIST',
  SET_SWAGGER = 'SET_SWAGGER',
  UPDATE_GLOBAL = 'UPDATE_GLOBAL',
  INCREMENT_ASYNC = 'INCREMENT_ASYNC',
  SET_COUNTER = 'SET_COUNTER',
}

export default CONSTANTS;
